"""Change role_id to NonNull

Revision ID: 6164206f50b3
Revises: 47e006b517aa
Create Date: 2024-07-08 20:06:55.360813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6164206f50b3'
down_revision = '47e006b517aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
